apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: realestate
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080
  # Change to NodePort if LoadBalancer is not available:
  # type: NodePort
